
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ClientScalarFieldEnum = {
  id: 'id',
  commercialName: 'commercialName',
  legalName: 'legalName',
  cifNif: 'cifNif',
  fiscalAddress: 'fiscalAddress',
  deliveryAddress: 'deliveryAddress',
  email: 'email',
  billingEmail: 'billingEmail',
  phone: 'phone',
  contactPerson: 'contactPerson',
  type: 'type',
  agreementId: 'agreementId',
  paymentTermId: 'paymentTermId',
  observations: 'observations',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CommercialAgreementScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  paramX: 'paramX',
  paramY: 'paramY',
  paramFloat: 'paramFloat'
};

exports.Prisma.PaymentTermScalarFieldEnum = {
  id: 'id',
  name: 'name',
  days: 'days'
};

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  boxSize: 'boxSize'
};

exports.Prisma.LocationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  isDefault: 'isDefault'
};

exports.Prisma.StockMovementScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  quantity: 'quantity',
  type: 'type',
  productCost: 'productCost',
  date: 'date',
  stockBefore: 'stockBefore',
  stockAfter: 'stockAfter',
  reason: 'reason',
  user: 'user',
  fromLocationId: 'fromLocationId',
  toLocationId: 'toLocationId',
  referenceId: 'referenceId'
};

exports.Prisma.OrderScalarFieldEnum = {
  id: 'id',
  clientId: 'clientId',
  date: 'date',
  status: 'status',
  boxesRojo: 'boxesRojo',
  boxesBlanco: 'boxesBlanco',
  bottlesRojo: 'bottlesRojo',
  bottlesBlanco: 'bottlesBlanco',
  promoRojo: 'promoRojo',
  promoBlanco: 'promoBlanco',
  totalBottles: 'totalBottles',
  productCost: 'productCost'
};

exports.Prisma.DeliveryNoteScalarFieldEnum = {
  id: 'id',
  number: 'number',
  orderId: 'orderId',
  date: 'date'
};

exports.Prisma.InvoiceScalarFieldEnum = {
  id: 'id',
  number: 'number',
  orderId: 'orderId',
  date: 'date',
  subtotal: 'subtotal',
  vat: 'vat',
  total: 'total',
  status: 'status',
  emailStatus: 'emailStatus',
  dueDate: 'dueDate'
};

exports.Prisma.InvoiceLineScalarFieldEnum = {
  id: 'id',
  invoiceId: 'invoiceId',
  description: 'description',
  quantity: 'quantity',
  unitPrice: 'unitPrice',
  discount: 'discount',
  total: 'total'
};

exports.Prisma.TransactionScalarFieldEnum = {
  id: 'id',
  type: 'type',
  status: 'status',
  amount: 'amount',
  paidAmount: 'paidAmount',
  expectedMethod: 'expectedMethod',
  dueDate: 'dueDate',
  date: 'date',
  clientId: 'clientId',
  supplierId: 'supplierId',
  referenceId: 'referenceId'
};

exports.Prisma.PaymentMovementScalarFieldEnum = {
  id: 'id',
  transactionId: 'transactionId',
  amount: 'amount',
  date: 'date',
  method: 'method',
  notes: 'notes'
};

exports.Prisma.SupplierScalarFieldEnum = {
  id: 'id',
  name: 'name',
  cifNif: 'cifNif'
};

exports.Prisma.PurchaseScalarFieldEnum = {
  id: 'id',
  supplierId: 'supplierId',
  date: 'date',
  total: 'total'
};

exports.Prisma.ExpenseScalarFieldEnum = {
  id: 'id',
  supplierName: 'supplierName',
  documentNo: 'documentNo',
  concept: 'concept',
  category: 'category',
  baseAmount: 'baseAmount',
  vatPercent: 'vatPercent',
  vatAmount: 'vatAmount',
  amount: 'amount',
  isPaid: 'isPaid',
  dueDate: 'dueDate',
  date: 'date',
  eventId: 'eventId'
};

exports.Prisma.EventScalarFieldEnum = {
  id: 'id',
  name: 'name',
  place: 'place',
  date: 'date',
  status: 'status',
  revenue: 'revenue',
  locationId: 'locationId'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.Role = exports.$Enums.Role = {
  ADMIN: 'ADMIN',
  USER: 'USER'
};

exports.ClientType = exports.$Enums.ClientType = {
  DISTRIBUIDOR: 'DISTRIBUIDOR',
  HOSTELERIA: 'HOSTELERIA',
  PARTICULAR: 'PARTICULAR'
};

exports.AgreementType = exports.$Enums.AgreementType = {
  NONE: 'NONE',
  PROMO_X_Y: 'PROMO_X_Y',
  DISCOUNT_PERCENT: 'DISCOUNT_PERCENT',
  SPECIAL_PRICE: 'SPECIAL_PRICE',
  MANUAL: 'MANUAL'
};

exports.ProductType = exports.$Enums.ProductType = {
  ROJO: 'ROJO',
  BLANCO: 'BLANCO'
};

exports.MovementType = exports.$Enums.MovementType = {
  BOTTLING: 'BOTTLING',
  PURCHASE: 'PURCHASE',
  SALE: 'SALE',
  TRANSFER: 'TRANSFER',
  PROMOTION: 'PROMOTION',
  REPLACEMENT: 'REPLACEMENT',
  SAMPLE: 'SAMPLE',
  TASTING: 'TASTING',
  EVENT: 'EVENT',
  COURTESY: 'COURTESY',
  BREAKAGE: 'BREAKAGE',
  SHRINKAGE: 'SHRINKAGE',
  INTERNAL: 'INTERNAL',
  ADJUSTMENT: 'ADJUSTMENT',
  RETURN: 'RETURN',
  OTHER: 'OTHER'
};

exports.InvoiceStatus = exports.$Enums.InvoiceStatus = {
  DRAFT: 'DRAFT',
  ISSUED: 'ISSUED',
  CANCELED: 'CANCELED'
};

exports.EmailStatus = exports.$Enums.EmailStatus = {
  PENDING: 'PENDING',
  SENDING: 'SENDING',
  SENT: 'SENT',
  ERROR: 'ERROR'
};

exports.TransactionType = exports.$Enums.TransactionType = {
  RECEIVABLE: 'RECEIVABLE',
  PAYABLE: 'PAYABLE'
};

exports.TransactionStatus = exports.$Enums.TransactionStatus = {
  PENDING: 'PENDING',
  PARTIAL: 'PARTIAL',
  PAID: 'PAID'
};

exports.Prisma.ModelName = {
  User: 'User',
  Client: 'Client',
  CommercialAgreement: 'CommercialAgreement',
  PaymentTerm: 'PaymentTerm',
  Product: 'Product',
  Location: 'Location',
  StockMovement: 'StockMovement',
  Order: 'Order',
  DeliveryNote: 'DeliveryNote',
  Invoice: 'Invoice',
  InvoiceLine: 'InvoiceLine',
  Transaction: 'Transaction',
  PaymentMovement: 'PaymentMovement',
  Supplier: 'Supplier',
  Purchase: 'Purchase',
  Expense: 'Expense',
  Event: 'Event'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
